version: "3"
services:
  db:
    image: postgres:12
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  mqtt-broker:
    image: emqx:5.4.0
    ports:
      - ${MQTT_PORT}:1883
      - ${MQTT_WS_PORT}:8083
      - ${MQTT_WEB_UI_PORT}:18083
    healthcheck:
      test:
        - CMD
        - /opt/emqx/bin/emqx
        - ctl
        - status
      interval: 5s
      timeout: 25s
      retries: 5
  redis_broker:
    container_name: ${REDIS_BROKER_HOST}
    image: redis:7
    ports:
      - ${REDIS_BROKER_PORT}:6379
    volumes:
      - redis_broker:/redis-broker-data
volumes:
  postgres: ~
  redis_broker:
    driver: local
